### ISSUE TITLE
bug? in `gizmo_agent`

### ISSUE THREAD

**Issue by leo-gan** [langchain-ai/opengpts#107]
I'm getting this error on a test [tests/unit_tests/test_imports.py:28 (test_gizmo_agent)]
It could be a failure in my environment (python 3.10.12). 
Maybe, it because gizmo_agent requires python 3.11 ([reference](https://docs.python.org/3/library/enum.html?highlight=enum#enum.StrEnum))

> FAILED                                 [ 75%]
> tests/unit_tests/test_imports.py:28 (test_gizmo_agent)
> def test_gizmo_agent() -> None:
>         """Test gizmo agent."""
>         # Shallow test to verify that teh code can be imported
>         with MonkeyPatch.context() as mp:
>             mp.setenv("OPENAI_API_KEY", "no_such_key")
> >           import gizmo_agent  # noqa: F401
> 
> test_imports.py:34: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> ../../packages/gizmo-agent/gizmo_agent/__init__.py:2: in <module>
>     from gizmo_agent.main import agent
> ../../packages/gizmo-agent/gizmo_agent/main.py:3: in <module>
>     from agent_executor.checkpoint import RedisCheckpoint
> ../../packages/agent-executor/agent_executor/checkpoint.py:10: in <module>
>     from permchain.checkpoint.base import BaseCheckpointAdapter
> /home/leo/.cache/pypoetry/virtualenvs/opengpts-CV_Z5uVz-py3.10/lib/python3.10/site-packages/permchain/__init__.py:2: in <module>
>     from permchain.pregel import Channel, Pregel, ReservedChannels
> /home/leo/.cache/pypoetry/virtualenvs/opengpts-CV_Z5uVz-py3.10/lib/python3.10/site-packages/permchain/pregel/__init__.py:56: in <module>
>     from permchain.pregel.reserved import ReservedChannels
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> >   from enum import StrEnum
> E   ImportError: cannot import name 'StrEnum' from 'enum' (/usr/lib/python3.10/enum.py)
> 
> /home/leo/.cache/pypoetry/virtualenvs/opengpts-CV_Z5uVz-py3.10/lib/python3.10/site-packages/permchain/pregel/reserved.py:1: ImportError
>

**Comment by nfcampos** [comment]
This has been resolved
