### ISSUE TITLE
Installation and Running with Docker Quick Start results in an error

### ISSUE THREAD

**Issue by malexw** [langchain-ai/opengpts#109]
Following along with the instructions in the README.md, I ran these commands:

```
git clone https://github.com/langchain-ai/opengpts.git
cd opengpts
docker compose up
```

And received this error while building the `backend` container:

```
failed to solve: process "/bin/sh -c rm poetry.lock" did not complete successfully: exit code: 1
```

Looking at the history of `./backend/Dockerfile`, I saw this commit: https://github.com/langchain-ai/opengpts/commit/d72f41284b8c3b32e46bd447f255989675010e0d

When I undo that commit, the backend container successfully builds and starts. If the containers are already successfully built and running for you, then running the rebuild command `docker-compose up --build` with the above commit in place also seems to trigger that error.

**Comment by ymg2007** [comment]
Yeah, I got the same error. 
` => [backend 2/6] RUN apt-get update && apt-get install -y libmagic1 && rm -rf /var/lib/apt/lists/*                                                                                                          5.2s
 => [frontend 2/6] WORKDIR /frontend                                                                                                                                                                         0.1s
 => [frontend 3/6] COPY ./frontend/package.json ./                                                                                                                                                           0.1s
 => [frontend 4/6] COPY ./frontend/yarn.lock ./                                                                                                                                                              0.0s
 => CANCELED [frontend 5/6] RUN yarn install                                                                                                                                                                 5.7s
 => [backend 3/6] WORKDIR /backend                                                                                                                                                                           0.0s
 => [backend 4/6] COPY . .                                                                                                                                                                                   0.2s
 => ERROR [backend 5/6] RUN rm poetry.lock                                                                                                                                                                   0.4s
------
 > [backend 5/6] RUN rm poetry.lock:
0.328 rm: cannot remove 'poetry.lock': No such file or directory
------
failed to solve: process "/bin/sh -c rm poetry.lock" did not complete successfully: exit code: 1
`

**Comment by WSDzju** [comment]
so how to fix this problem?

**Comment by WSDzju** [comment]
> so how to fix this problem?

got it. revise the Dockerfile

**Comment by ymg2007** [comment]
how to revise the Dockerfile? please post the new code @WSDzju

**Comment by malexw** [comment]
I see that PR #108 is intended to fix this

**Comment by ymg2007** [comment]
OK,I got it.Just delete the line
`Run rm poetry.lock`

**Comment by kattapug** [comment]
I have the similar issues. I removed this line from the docker file. Now get the error below.  Any suggestions?

 => ERROR [backend 6/6] RUN pip install .                                                                          0.9s
------
 > [backend 6/6] RUN pip install .:
0.744 ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
------
failed to solve: process "/bin/sh -c pip install ." did not complete successfully: exit code: 1

(base) C:\Dev\opengpts>

**Comment by malexw** [comment]
You don't need to remove any lines from the docker file. Just do the opposite of what was in this commit: https://github.com/langchain-ai/opengpts/commit/d72f41284b8c3b32e46bd447f255989675010e0d

**Comment by kattapug** [comment]
> You don't need to remove any lines from the docker file. Just do the opposite of what was in this commit: [d72f412](https://github.com/langchain-ai/opengpts/commit/d72f41284b8c3b32e46bd447f255989675010e0d)

Thanks it worked.

**Comment by Qinnnnnn** [comment]
这是我的Dockerfile
```
# Backend Dockerfile
FROM python:3.11

# Install system dependencies
RUN apt-get update && apt-get install -y libmagic1 && rm -rf /var/lib/apt/lists/*

# Copy the working directory
COPY . .

# Set the working directory
WORKDIR /backend

RUN rm poetry.lock

RUN pip install .

CMD exec uvicorn app.server:app --host 0.0.0.0 --port $PORT
```

**Comment by shacharbard** [comment]
do what @Qinnnnnn suggested.
replace between the lines COPY . .  and WORKDIR /backend
that fixes the issue. no need to delete anything!
