### ISSUE TITLE
openai.AuthenticationError

### ISSUE THREAD

**Issue by world4jason** [langchain-ai/opengpts#154]
> openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: placeholder. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

This issue occurs when I select 'GPT-4 (Azure OpenAI)' in both the RAG tab and Assistant tab, but Chat mode functions perfectly.

**Comment by ArneJanning** [comment]
As of today, it works in the assistant tab but still fails in the RAG tab.

**Comment by ArneJanning** [comment]
The issue exists because OpenAIs Embedding models are hard-coded into RAG and "Retrieval".

To use RAG with Azure OpenAI you have to change `./backend/app/upload.py`. 

Add:
`from langchain_openai import AzureOpenAIEmbeddings`

to the import-section and add/change:

`embeddings = AzureOpenAIEmbeddings(
    azure_deployment="<Your_Embedding_Model_Deployment_Name_On_Azure>",
    openai_api_version="2023-09-01-preview",
    openai_api_key=os.environ["AZURE_OPENAI_API_KEY"],
    azure_endpoint=os.environ["AZURE_OPENAI_API_BASE"],
)

vstore = Redis(
    redis_url=os.environ["REDIS_URL"],
    index_name="opengpts",
    #embedding=OpenAIEmbeddings(),
    embedding=embeddings,
    index_schema=index_schema,
)
`

And then it works.

**Comment by world4jason** [comment]
@ArneJanning After that changes, it works!, but do you encounter following issue?
https://github.com/langchain-ai/opengpts/issues/93

**Comment by world4jason** [comment]
```python
vstore = Redis(
    redis_url=os.environ["REDIS_URL"],
    index_name="opengpts",
    embedding=embeddings,
    index_schema=index_schema,
)
vstore._create_index_if_not_exist()

```

bug from langchain, solved by this workaround
