### ISSUE TITLE
GPTs: a simple hosted version doesn't work

### ISSUE THREAD

**Issue by hchenphd** [langchain-ai/opengpts#193]
https://opengpts-example-vz4y4ooboq-uc.a.run.app

always shows saving when creating new bot

**Comment by ByeongUkChoi** [comment]
+1

**Comment by mkorpela** [comment]
@hchenphd Thank you for the report. The instance is now up and running. Tested also that saving a bot worked.

Feel free to open a new issue if the situation persists.
