### ISSUE TITLE
Redis db wiped out every day

### ISSUE THREAD

**Issue by thierryteisseire** [langchain-ai/opengpts#210]
hello team,

I am a big fan of what of you have build here. thank you!

To whoever might know why the redis db in 2 backends I have running are back to zero size - get flushed everyday. 

Here the docker logs:
30:C 01 Mar 2024 15:09:17.067 * DB saved on disk
30:C 01 Mar 2024 15:09:17.068 * Fork CoW for RDB: current 1 MB, peak 1 MB, average 1 MB
8:M 01 Mar 2024 15:09:17.146 * Background saving terminated with success
8:M 01 Mar 2024 16:09:18.064 * 1 changes in 3600 seconds. Saving...
8:M 01 Mar 2024 16:09:18.065 * Background saving started by pid 31
31:C 01 Mar 2024 16:09:18.096 * DB saved on disk
31:C 01 Mar 2024 16:09:18.097 * Fork CoW for RDB: current 1 MB, peak 1 MB, average 1 MB
8:M 01 Mar 2024 16:09:18.166 * Background saving terminated with success
8:M 01 Mar 2024 17:08:32.663 * 100 changes in 300 seconds. Saving...
8:M 01 Mar 2024 17:08:32.664 * Background saving started by pid 32
32:C 01 Mar 2024 17:08:32.695 * DB saved on disk
32:C 01 Mar 2024 17:08:32.696 * Fork CoW for RDB: current 1 MB, peak 1 MB, average 1 MB
8:M 01 Mar 2024 17:08:32.765 * Background saving terminated with success
8:M 01 Mar 2024 17:13:33.084 * 100 changes in 300 seconds. Saving...
8:M 01 Mar 2024 17:13:33.085 * Background saving started by pid 33
33:C 01 Mar 2024 17:13:33.109 * DB saved on disk
33:C 01 Mar 2024 17:13:33.110 * Fork CoW for RDB: current 1 MB, peak 1 MB, average 1 MB
8:M 01 Mar 2024 17:13:33.185 * Background saving terminated with success
8:M 01 Mar 2024 17:18:31.829 * <redisgears_2> Got a flush started event
8:M 01 Mar 2024 17:18:31.833 * <redisgears_2> Got a flush started event
8:M 01 Mar 2024 17:18:31.862 * <redisgears_2> Got a flush started event
8:M 01 Mar 2024 17:18:31.864 * <redisgears_2> Got a flush started event
8:M 01 Mar 2024 17:18:33.030 * <redisgears_2> Got a flush started event
8:M 01 Mar 2024 17:18:33.078 * <redisgears_2> Got a flush started event
8:M 01 Mar 2024 17:18:33.771 * <redisgears_2> Got a flush started event
8:M 01 Mar 2024 17:18:33.843 * <redisgears_2> Got a flush started event
8:M 01 Mar 2024 17:18:34.035 * 100 changes in 300 seconds. Saving...
8:M 01 Mar 2024 17:18:34.035 * Background saving started by pid 35
35:C 01 Mar 2024 17:18:34.042 * DB saved on disk
35:C 01 Mar 2024 17:18:34.043 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
8:M 01 Mar 2024 17:18:34.136 * Background saving terminated with success
8:S 01 Mar 2024 17:18:34.538 * Before turning into a replica, using my own master parameters to synthesize a cached master: I may be able to synchronize with the new master with just a partial transfer.
8:S 01 Mar 2024 17:18:34.538 * <redisgears_2> Role changed to replica, abort all async commands invocation.
8:S 01 Mar 2024 17:18:34.538 * Connecting to MASTER 58.209.234.96:60146
8:S 01 Mar 2024 17:18:34.538 * MASTER <-> REPLICA sync started
8:S 01 Mar 2024 17:18:34.538 * REPLICAOF 58.209.234.96:60146 enabled (user request from 'id=1740 addr=154.92.110.140:8401 laddr=172.29.0.2:6379 fd=24 name= age=3 idle=0 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 qbuf=29 qbuf-free=20445 argv-mem=25 multi-mem=0 rbs=1024 rbp=155 obl=0 oll=0 omem=0 tot-mem=22449 events=r cmd=slaveof user=default redir=-1 resp=2 lib-name= lib-ver=')
8:S 01 Mar 2024 17:18:35.076 * REPLICAOF would result into synchronization with the master we are already connected with. No operation performed.
8:S 01 Mar 2024 17:18:35.267 * REPLICAOF would result into synchronization with the master we are already connected with. No operation performed.
8:S 01 Mar 2024 17:18:35.302 * REPLICAOF would result into synchronization with the master we are already connected with. No operation performed.
8:S 01 Mar 2024 17:18:35.881 * Non blocking connect for SYNC fired the event.
8:S 01 Mar 2024 17:18:37.033 * Master replied to PING, replication can continue...
8:S 01 Mar 2024 17:18:37.678 * Trying a partial resynchronization (request 7d8e9aa2b15438eb1b69ac583d87ce49100b5c48:1).
8:S 01 Mar 2024 17:18:37.975 * Full resync from master: ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ:0
8:S 01 Mar 2024 17:18:37.975 * MASTER <-> REPLICA sync: receiving 21816 bytes from master to disk
8:S 01 Mar 2024 17:18:39.299 * Discarding previously cached master state.
8:S 01 Mar 2024 17:18:39.300 * MASTER <-> REPLICA sync: Flushing old data
8:S 01 Mar 2024 17:18:39.300 * <redisgears_2> Got a flush started event
8:S 01 Mar 2024 17:18:39.300 * MASTER <-> REPLICA sync: Loading DB in memory
8:S 01 Mar 2024 17:18:39.306 * <search> Loading event starts
8:S 01 Mar 2024 17:18:39.306 * <redisgears_2> Got a loading start event, clear the entire functions data.
8:S 01 Mar 2024 17:18:39.306 # Wrong signature trying to load DB from file
8:S 01 Mar 2024 17:18:39.306 * <redisgears_2> Loading finished, re-enable key space notificaitons.
8:S 01 Mar 2024 17:18:39.306 # Failed trying to load the MASTER synchronization DB from disk, check server logs.
8:S 01 Mar 2024 17:18:39.306 * Reconnecting to MASTER 58.209.234.96:60146 after failure
8:S 01 Mar 2024 17:18:39.306 * MASTER <-> REPLICA sync started
8:S 01 Mar 2024 17:18:39.569 * Non blocking connect for SYNC fired the event.
8:S 01 Mar 2024 17:18:39.835 * Master replied to PING, replication can continue...
8:M 01 Mar 2024 17:18:40.119 * Setting secondary replication ID to 7d8e9aa2b15438eb1b69ac583d87ce49100b5c48, valid up to offset: 1. New replication ID is 677a9cbabc21d837d3de28f37f77089278068076
8:M 01 Mar 2024 17:18:40.119 * <redisgears_2> Role changed to primary, initializing key scan to search for streams.
8:M 01 Mar 2024 17:18:40.119 * MASTER MODE enabled (user request from 'id=1740 addr=154.92.110.140:8401 laddr=172.29.0.2:6379 fd=24 name= age=9 idle=0 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 qbuf=16 qbuf-free=20458 argv-mem=12 multi-mem=0 rbs=1024 rbp=223 obl=0 oll=0 omem=0 tot-mem=22436 events=r cmd=slaveof user=default redir=-1 resp=2 lib-name= lib-ver=')
8:M 01 Mar 2024 17:21:25.275 * <redisgears_2> Got a flush started event
8:M 01 Mar 2024 18:18:35.040 * 1 changes in 3600 seconds. Saving...
8:M 01 Mar 2024 18:18:35.041 * Background saving started by pid 37
37:C 01 Mar 2024 18:18:35.047 * DB saved on disk
37:C 01 Mar 2024 18:18:35.049 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
8:M 01 Mar 2024 18:18:35.142 * Background saving terminated with success

I did set up on 1 db AOF but still same behaviour.
Anyone have a clue?

Thanks all,

**Comment by tomknightai** [comment]
I am seeing the same problem.  Redis is flushing its database.  This happens periodically every hour or so. 

This has occurred when running with Docker on Ubuntu 20.04 and Ubuntu 23.10.

I am not seeing this problem when running with Docker on Windows 11.

**Comment by tomknightai** [comment]
I can confirm that switching from Redis to Postgres has resolved this issue.  Thanks!
