### ISSUE TITLE
PostgreSQL Configuration in Docker via .env Not Applied

### ISSUE THREAD

**Issue by shamspias** [langchain-ai/opengpts#246]
I'm encountering an issue with configuring PostgreSQL within a Docker container using environment variables specified in a `.env` file. Despite updating the repository and setting the PostgreSQL configuration in the `.env` file, the changes don't seem to be applied, leading to errors when starting the container.

**Environment Configuration (.env):**

```plaintext
POSTGRES_PORT=5432
POSTGRES_DB=opengpt
POSTGRES_USER=opengpt
POSTGRES_PASSWORD=opengpt
```

**Steps to Reproduce:**

1. Update the repository to include the above PostgreSQL configuration in the `.env` file.
2. Remove existing Docker images and containers to ensure a clean state.
3. Rebuild and start the Docker containers using the updated `.env` file.

**Expected Behavior:**

The PostgreSQL container starts with the specified configuration, allowing other services to connect using the provided credentials and database name.

**Actual Behavior:**

The PostgreSQL container logs indicate that it skips initialization due to an existing database directory, and subsequent logs show errors related to the database not existing and password authentication failing for user "opengpt".

**Error Logs:**

```plaintext
ttaching to opengpts-backend, opengpts-frontend, postgres-1, postgres-setup-1
postgres-1         | 
postgres-1         | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres-1         | 
postgres-1         | 2024-03-21 08:42:30.789 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres-1         | 2024-03-21 08:42:30.789 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres-1         | 2024-03-21 08:42:30.789 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres-1         | 2024-03-21 08:42:30.795 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-1         | 2024-03-21 08:42:30.803 UTC [29] LOG:  database system was shut down at 2024-03-21 08:41:51 UTC
postgres-1         | 2024-03-21 08:42:30.809 UTC [1] LOG:  database system is ready to accept connections
postgres-1         | 2024-03-21 08:42:31.810 UTC [40] FATAL:  database "opengpt" does not exist
postgres-1         | 2024-03-21 08:42:32.466 UTC [41] FATAL:  password authentication failed for user "opengpt"
postgres-1         | 2024-03-21 08:42:32.466 UTC [41] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
postgres-setup-1   | error: pq: password authentication failed for user "opengpt"
postgres-setup-1 exited with code 1
service "postgres-setup" didn't complete successfully: exit 1
```

**Additional Information:**

- I've tried varying the `.env` values and ensuring that there are no typos or errors in the variable names.
- The issue persists even after cleaning Docker images and containers to ensure there's no stale configuration.

Any insights or suggestions on resolving this issue would be greatly appreciated.

**Comment by bakar-io** [comment]
Given the fact that logs show `PostgreSQL Database directory appears to contain a database; Skipping initialization`, I believe that you already initialized the database with other env vars than the ones you are currently trying to use. Here's what to try: delete the `postgres-volume` and run docker again. Should work.
