### ISSUE TITLE
Seems like a docker image from a different repo has been pushed as the open-gpts latest

### ISSUE THREAD

**Issue by xmile1** [langchain-ai/opengpts#251]
I pulled the latest image and i got a different UI (LangGraph Studio), while investigating I realized there might have been a wrong image deployed to docker hub.

The latest tag is [affb0e1](https://hub.docker.com/layers/langchain/open-gpts/affb0e1/images/sha256-30f6db53fc4103e18d19c7951d48e8174c3a2339df7dcc5d7147382fa2ddef9e?context=explore) which seems to be coming from elsewhere.

From the last deployment [Update README.md docker doc to reflect switch to postgres](https://github.com/langchain-ai/opengpts/actions/runs/8399548297/job/23005787782#step:7:1747) its seems the latest docker tag should be 61d3e9c
Using 61d3e9c gives the expected UI

UI with the latest docker image
![Screenshot 2024-03-23 at 10 14 51](https://github.com/langchain-ai/opengpts/assets/16453210/d8d42479-ec3b-40b9-88ce-a31ba46142b3)

Tagging @mkorpela since he did the last working deployment

**Comment by nfcampos** [comment]
This has been fixed as of `[dd4b9f7](https://hub.docker.com/layers/langchain/open-gpts/dd4b9f7/images/sha256-856acd64d9a8fcd686eb3682ccf681bcda81172156b3d6737227d3d9fff15a33?context=explore)`, sorry about that
