### ISSUE TITLE
Issue with Ingesting/Upserting CSV File in opengpts-backend

### ISSUE THREAD

**Issue by thierryteisseire** [langchain-ai/opengpts#308]
Running last version clean from git pull on Ubuntu 20.

<img width="794" alt="Screenshot 2024-04-16 184003" src="https://github.com/langchain-ai/opengpts/assets/77529835/143670f9-de82-4bb5-8e53-1a811fc204c4">

Description:
I am currently running the latest version of opengpts-backend after a clean git pull on Ubuntu 20. However, I am encountering an issue where I am unable to ingest/upsert a CSV file. The error message I am receiving is as follows:

File "/backend/app/ingest.py", line 45, in ingest_blob
for document in parser.lazy_parse(blob):
File "/usr/local/lib/python3.11/site-packages/langchain_community/document_loaders/parsers/generic.py", line 70, in lazy_parse
raise ValueError(f"Unsupported mime type: {mimetype}")
ValueError: Unsupported mime type: text/csv
I have attached a screenshot for reference: [Screenshot](https://github.com/langchain-ai/opengpts/assets/77529835/143670f9-de82-4bb5-8e53-1a811fc204c4)

I am seeking assistance in understanding why CSV files are not allowed for ingestion in opengpts-backend. Any insights or guidance on resolving this issue would be greatly appreciated.

**Comment by thierryteisseire** [comment]
I realised we do not cover csv upserting.

**Comment by zhangsanfenggpt** [comment]
I got the same problem , has any solution?
