### ISSUE TITLE
"AI Safety" Regulatory Compliance

### ISSUE THREAD

**Issue by chadbrewbaker** [langchain-ai/opengpts#55]
There needs to be something in the README about regulatory compliance.

Real "AI Safety" is traditional cybersecurity.

Hopefully in the near future there should be a @tinygrad library - simple formally verified parsers around the LLM process.  That is *true* AI safety. Bonus aside you can use Valiant's result from 1970s that CFG == MATMUL, and use TinyGrad for parsing. Boolean MATMUL is bottleneck: https://www.cs.cornell.edu/home/llee/talks/bmmtalk.pdf

How should this messaging be reflected in the README to help users defend themselves from predatory  "AI Safety" companies extorting them?

This is what LLM proposed:

## The Truth About "AI Safety"
- **LLMs Are Autocomplete:** See [PicoGPT](https://github.com/jaymody/picoGPT/blob/main/gpt2_pico.py) - you can train a LLM in one page of Python given the US Library of Congress on USB stick. They are shocking because of their speed at searching library knowledge - putting advanced concepts in reach of the common man.
- **Direct Threat Acknowledgement:** All hardware is vulnerable to attacks, whether from humans or automated bots. Real safety is traditional cybersecurity best practices.
- **AI Safety as Censorship:** Corporations and governments misuse "AI safety" as pretext for technology hoarding, censorship, and maintaining power.
- **Extortion in Disguise:** Many companies claim to sell "AI safety" while manipulating fears for profit, effectively extortion rackets on lawful users of LLMs.

@oliviazhu - your input would be helpful. I want this project to have FedRAMP certified artifacts using already approved AWSLinux/RHEL packages.

**Comment by hwchase17** [comment]
not sure what exactly this is asking for. if the goal is `to help users defend themselves from predatory "AI Safety" companies extorting them` im not sure the readme of this package is the best place to reflect that. we have a section in langchain documentation on security, perhaps more applicable there
