### ISSUE TITLE
做一个简单的爬取24小时销量的数据 AI 已经完成但是代码运行出来的表格是空的

### ISSUE THREAD

**Issue by saber-qqq** [langchain-ai/opengpts#59]
做一个简单的爬取24小时销量的数据 AI 已经完成但是代码运行出来的表格是空的

**Comment by hwchase17** [comment]
not sure how to help, more info needed

**Comment by saber-qqq** [comment]
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time

# Initialize Chrome WebDriver
options = Options()
options.add_argument('--ignore-ssl-errors=yes')
options.add_argument('--ignore-certificate-errors')
options.headless = True  # Modify as needed
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# Navigate to DHgate homepage
driver.get("https://www.dhgate.com")

# Wait for the page to load
time.sleep(10)

# Find the search box and search for 'shoes'
search_box = driver.find_element(By.NAME, "searchkey")
search_box.send_keys("shoes")
search_box.send_keys(Keys.RETURN)

time.sleep(10)  # Wait for search results

# Sort by 24-hour sales ranking, if possible

# Scrape the top 500 product links
links = []
product_links = driver.find_elements(By.CSS_SELECTOR, "a.product-link")  # Adjust selector as needed
for link in product_links[:500]:
    links.append(link.get_attribute('href'))

# Close the WebDriver
driver.quit()

# Save the links in a DataFrame and then to a CSV file
df = pd.DataFrame(links, columns=["Product Link"])
df.to_csv("top_500_shoes_links.csv", index=False)

print("Top 500 product links for shoes saved to 'top_500_shoes_links.csv'")













脚本如上 基于谷歌游览器  想要获取的是shoes的类目的24小时的销量排行

**Comment by saber-qqq** [comment]
最直接点能不能让gtp可以访问外部网站 或者能基于gtp4上运行代码以便方便修改呢
