### ISSUE TITLE
The first question will launch the search tool, but no longer use the search tool for any further conversations

### ISSUE THREAD

**Issue by miandai** [langchain-ai/opengpts#8]
When starting a new conversation, the first question will launch the search tool, but no longer use the search tool for any further conversations, just llm answering, Is there someone know why?

**Comment by hwchase17** [comment]
@nfcampos is this a bug? will this be resolved in harrison/stateful branch?

**Comment by miandai** [comment]
The llm I used was chatglm3, not chatgpt. Because it's not convenient for me to access chatgpt here.

So maybe it's not a opengpts issue. I don't know if other people using chatgpt have encountered the same problem.
