### ISSUE TITLE
Why it requires always an OPENAI_API_KEY and does not switch zu Open-AI-Azure

### ISSUE THREAD

**Issue by ChristophEckerle** [langchain-ai/opengpts#99]
1. If I start the project out of the box with project tailored .env file, which has no "OPENAI_API_KEY", it always requires the key during booting the project. The workaround by giving him a dummy value works for that step: `"OPENAI_API_KEY: your_secret_key_here".`

2. After creating a bot and selecting via the GUI, GizmoAgentType="GPT 4 (Azure OpenAI)", see below part of the json payload from the client for the configured agents:

`configurable
: 
{agent_type: "GPT 4 (Azure OpenAI)",…}
agent_type
: 
"GPT 4 (Azure OpenAI)"
system_message
: 
"You are a helpful assistant for our customer service team to retrieve product data information "`

It still requires the OpenAI key:

`openai.error.AuthenticationError: Incorrect API key provided: my_dummy_key. You can find your API key at https://platform.openai.com/account/api-keys.
backend_1 `

The Azure OpenAI .env variables get somehow not sourced:

`AZURE_OPENAI_DEPLOYMENT_NAME: your_secret_here
AZURE_OPENAI_API_BASE: your_secret_here
AZURE_OPENAI_API_VERSION: your_secret_here
AZURE_OPENAI_API_KEY: your_secret_here`

**Comment by j-paris** [comment]
Any news on this topic (OPEN_AI_KEY always required and how to switch to Azure Open AI)?

**Comment by ArneJanning** [comment]
Same problem here and it's not at all clear why this happens.

**Comment by mkorpela** [comment]
should be now fixed https://github.com/langchain-ai/opengpts/pull/270/
